name = "Worph"
uuid = "0e74bb5c-d4ba-4f3d-9d9f-a0fc5badf327"
authors = ["joto "]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
CBindingGen = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"

[compat]
CBinding = "^0.9"
CBindingGen = "^0.3,^0.4"
